version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - my_network

  express:
    build:
      context: ./
    container_name: express
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
